os: linux
sudo: required
dist: xenial
services:
  - xvfb
  - postgresql
language: python
python:
- "3.9"
env:
  - NODE_ENV=production NODE_VERSION="10.23.0" DATABASE_URL="postgresql://localhost/travis_test"
branches:
  only:
  - master
  - staging
  - cs310-spring21
cache:
  apt: true
  directories:
  - node_modules
  - $HOME/.npm
  - $HOME/.cache/pip
before_install:
- sudo apt-get update
- sudo apt-get -y install python3 python3-pip
- sudo pip3 install --upgrade pip
install:
#- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#- sudo apt-get clean
#- sudo apt-get update
#- sudo apt-get install dpkg
#- sudo -E apt-get -yq --allow-unauthenticated install google-chrome-stable
- nvm install $NODE_VERSION
- npm -g install chromedriver
- npm -g install jest@20
- npm install
# - pip install --upgrade pip
# - pip install -r requirements.txt
- pip3 install --user numpy==$NUMPY_VERSION
- pip3 install --user scipy==$SCIPY_VERSION
- pip3 install --user requests==$REQST_VERSION
- pip3 install --user -r requirements.txt
addons:
  chrome: stable
#  apt:
#    sources:
#    - google-chrome
#    packages:
#    - google-chrome-stable
  hosts:
  - jhu.sem.ly
before_script:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
- npm run lint
- npm run test
- python3 manage.py test
- make html -C docs
