apiVersion : apps/v1
kind: Deployment
metadata:
  name: semesterly 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semesterly
  template:
    metadata:
      labels:
        app: semesterly 
    spec:
      containers:
        - name: semesterly 
          image: uisacr.azurecr.io/semesterlydev
          ports:
          - containerPort: 8000
